[TOC]

# 错误代码示例

```tsx
let arr: any[];
function test(key: number) {
  try {
    switch (key) {
      case 1:
        arr = new Array(-1);
        console.log(arr);
        throw new RangeError('RangeError 错误信息');
      case 2:
        throw new ReferenceError('ReferenceError 错误信息');
      case 3:
        eval('console.log("Eval 执行中"');
        throw new SyntaxError('SyntaxError 错误信息');
      case 4:
        throw new TypeError('TypeError 错误信息');
      case 5:
        throw new URIError('URIError 错误信息');
      default:
        throw new Error('错误信息');
    }
  } catch (error) {
    // 每个错误对象都有message
    console.log(error.message);
    console.log(error);
    return '我错了';
  } finally {
    console.log('ddd');
    // 这里的return 会使 try catch中的实效
    return '我错了，😭';
  }
}
console.log(test(5));
```
